"""create meeting_preps

Revision ID: 21aa76a3c936
Revises: 9b695191abf6
Create Date: 2026-08-10 18:00:21.192489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '21aa76a3c936'
down_revision: Union[str, Sequence[str], None] = '9b695191abf6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meeting_preps',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('physician_name', sa.Text(), nullable=True),
    sa.Column('specialty', sa.Text(), nullable=True),
    sa.Column('product', sa.Text(), nullable=False),
    sa.Column('objective', sa.Text(), nullable=False),
    sa.Column('output', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meeting_preps_user_id'), 'meeting_preps', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meeting_preps_user_id'), table_name='meeting_preps')
    op.drop_table('meeting_preps')
    # ### end Alembic commands ###
